from src.image_generator import create_images
from src.string_generator import generate_strings
from flask import Flask, render_template, request
import os
import random
import hashlib

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
IMAGE_NUMBER = 100  # The number of images and strings to be generated.
app = Flask(__name__)
str_combination = dict()


def get_hashes():
    """
    Retrieves hashes from the file.
    """
    with open(f"{BASE_DIR}\\static\\captcha_codes.txt", 'r') as f:
        for i in f:
            line = list(i.split(";"))
            str_combination[line[0]] = line[1].strip("\n").strip(" ")


@app.route('/')  # The main entry point.
def index():
    """
    Retrieves hashes, selects a random image index, and renders the template.
    """
    r_number = str(random.randint(0, IMAGE_NUMBER - 1))
    static_path = os.path.join(BASE_DIR, "static", "captcha_images")

    get_hashes()

    return render_template("index.html", r_number=r_number)


@app.route('/login', methods=['POST'])
def login():
    """
    Login function, triggered after the user submits the form or clicks the refresh CAPTCHA button.

    Retrieves data from the user form into corresponding variables.
    The CAPTCHA code inputted by the user is hashed.
    If the login is provided, the password is longer than 7 characters, and the user's CAPTCHA input is correct, the user successfully logs in.
    Otherwise, the site is rendered again and the user must input the data again.

    ##############################
    I used AI for Flask and the connection between the frontend and the backend.
    All frontend code (HTML, CSS) was generated by AI.
    ##############################
    """
    action = request.form.get('action')

    if action == 'refresh':  # Refresh CAPTCHA button logic.
        r_number = str(random.randint(0, IMAGE_NUMBER - 1))
        return render_template("index.html", r_number=r_number)

    u_code = request.form.get('u_captcha')  # Data retrieved from the user input.
    captcha_number = request.form.get("r_number")
    user_login = request.form.get("u_login")
    logged_in = False
    msg = ''

    captcha_code = hashlib.sha512(u_code.encode()).hexdigest()  # The user input is hashed.

    if not logged_in:  # Validates the user input (non-empty login, password longer than 7 characters, correct CAPTCHA code).
        if user_login is not None and len(request.form.get('u_password')) > 7 and captcha_code == str_combination[
            captcha_number]:
            logged_in = True
        else:
            logged_in = False
            msg = 'failure'

    if logged_in:  # If the user successfully logs in, they are greeted with 'Hello, [user_login]'.
        return render_template("user_page.html", user_login=user_login)
    else:  # In case of failure, a new image is chosen.
        r_number = str(random.randint(0, IMAGE_NUMBER - 1))
        return render_template("index.html", r_number=r_number, msg=msg)


if __name__ == '__main__':  # First, strings and images are generated.
    generate_strings(IMAGE_NUMBER)
    create_images(IMAGE_NUMBER)

    app.run(debug=False)  # Starts the application.